apiVersion: v1
kind: Pod
metadata:
    name: es
    labels:
        app: es
spec:
    containers:
        - name: elastic-search
          image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0 
        - name: kibana
          image: docker.elastic.co/kibana/kibana-oss:6.3.0
          env:
            - name: ELASTICSEARCH_URL
              value: http://localhost:9200
