apiVersion: v1
kind: Service
metadata:
  name: es
spec:
  selector:
    app: es
  ports:
    - port: 9200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es
  labels:
    deployment: es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
        - name: elastic-search
          image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
          ports:
          - containerPort: 9200
            protocol: TCP
