apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops
  labels:
    deployment: ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ops
  template:
    metadata:
      labels:
        app: ops
    spec:
      containers:
        - name: ops
          image: solita/ubuntu-systemd
